### ISSUE TITLE
Error While Parsing the m3u8 Url

### ISSUE THREAD

**Issue by abhishek8298** [futzu/m3ufu#3]
Traceback (most recent call last):
  File "/usr/local/bin/m3ufu", line 5, in <module>
    cli()
  File "/usr/local/lib/pypy3.6/dist-packages/m3ufu.py", line 624, in cli
    fu.decode()
  File "/usr/local/lib/pypy3.6/dist-packages/m3ufu.py", line 611, in decode
    if not self._parse_line():
  File "/usr/local/lib/pypy3.6/dist-packages/m3ufu.py", line 594, in _parse_line
    self._do_media(line)
  File "/usr/local/lib/pypy3.6/dist-packages/m3ufu.py", line 560, in _do_media
    self._add_media(media)
  File "/usr/local/lib/pypy3.6/dist-packages/m3ufu.py", line 537, in _add_media
    segment = Segment(self.chunk, media, self._start, self.base_uri)
  File "/usr/local/lib/pypy3.6/dist-packages/m3ufu.py", line 258, in __init__
    self.relative_uri = media_uri.removeprefix(base_uri)
AttributeError: 'str' object has no attribute 'removeprefix'

**Comment by futzu** [comment]
Glad to see you're running pypy3, everything runs better on pypy3

* **what version m3ufu are you running?**
     * the latest is v.0.0.69
     * if you don't have v.0.0.69, upgrade and that will probably fix it. 

**If upgrading doesn't fix it;** 
*  I need to know what command you ran
*  the m3u8 url 
* the output prior to the traceback so I can see what it was doing when it happened.

**Comment by futzu** [comment]
you cool?

**Comment by futzu** [comment]
If you still  have problems, re-open the issue.
